name: myFlutterApp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

fonts:
  - family: Schyler
    fonts:
      - asset: fonts/Schyler-Regular.ttf
      - asset: fonts/Schyler-Italic.ttf
        style: italic
  - family: Trajan Pro
    fonts:
      - asset: fonts/TrajanPro.ttf
      - asset: fonts/TrajanPro_Bold.ttf
        weight: 700

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: any
  json_annotation: any
  http: ^0.13.5
  retrofit: any
  logger: any
  dio: ^5.3.2
  file_picker: any
  cupertino_icons: ^1.0.0
  dartz: ^0.10.1
  progress_indicators: ^1.0.0
  dots_indicator: ^3.0.0
  get_it: ^7.6.0
  json_serializable: ^6.5.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  build_runner: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  flutter_driver:
    sdk: flutter
  retrofit_generator: any
  image_test_utils: ^1.0.0
  mockito: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true


